{% set name = "pyngrok" %}
{% set version = "2.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 69ff860bedcdfd8175b2e22af92c1d4cbb9736c9ec121441cbe60d483a5b45c0

build:
  noarch: python
  entry_points:
    - ngrok=pyngrok.ngrok:main
    - pyngrok=pyngrok.ngrok:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - future
    - PyYAML
  run:
    - python

test:
  imports:
    - pyngrok

about:
  home: https://github.com/alexdlaird/pyngrok
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper for ngrok
  description: |
    pyngrok is a Python wrapper for ngrok that manages its own binary and puts it on our path,
    making ngrok readily available from anywhere on the command line and via a convenient
    Python API.
  doc_url: https://pyngrok.readthedocs.io/
  dev_url: https://github.com/alexdlaird/pyngrok

extra:
  recipe-maintainers:
    - alexdlaird
